import type { Metadata } from "next";
import "@/css/globals.css";
import { fontPretendard } from "@/css/font";
import Header from "@/app/_components/header/Header";
import Footer from "app/_components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontPretendard.className} font-pretendard`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
